### ISSUE TITLE
Reverse Mask for Money Format

### ISSUE THREAD

**Issue by gabrielbuzziv** [react-native-text-input-mask/react-native-text-input-mask#51]
Is possible to add a reverse option, so i can use this mask package for money format?

**Comment by lutchobandeira** [comment]
Hi, I am trying to reverse the mask in order to make a proper money format as well.

I took a look at the native projects (android and ios) and I could see that it is possible to use a reversed mask on the native side (```ReversedMaskTextFieldDelegate``` for ios and ```ReversedMaskTextChangedListener``` for android).

These classes are not documented though. So I am a little bit confused of how to change this project in order to make possible to use this feature from the react native side.

**Comment by romulogarofalo** [comment]
@lutchobandeira where did u put the ReversedMaskTextChangedListener ? can u show the code?

**Comment by guilherme-ramalho** [comment]
Any progress on that?
