### ISSUE TITLE
Mask does not work with floating label

### ISSUE THREAD

**Issue by kgoedert** [react-native-text-input-mask/react-native-text-input-mask#89]
Hi,
I would like to use the mask component, inside an item with a floating label, like this:

```
 <Item floatingLabel>
      <Label>Tel</Label>
      <TextInputMask
              refInput={ref => {
                this.input = ref;
              }}
              onChangeText={(formatted, extracted) => {
                console.log(formatted); // +1 (123) 456-78-90
                console.log(extracted); // 1234567890
              }}
              mask={'+1 ([000]) [000] [00] [00]'}
            />
</Item>
```
But the mask is not rendered. Should this work? Using the TextInputMask outside the Item works without problems.

**Comment by marcogorak** [comment]
I'm have the same problem =/

**Comment by marcogorak** [comment]
I search about it, I see that native base rewrite the Input in <Item></Item> tags, see this print of doc:

![Captura de Tela 2019-04-25 às 09 39 10](https://user-images.githubusercontent.com/12548136/56736279-23eeda00-673e-11e9-9d97-cd841e34c87f.png)
Font: https://docs.nativebase.io/Components.html#inline-label-headref

One way to solve this problem is using one workound with react-native-masked-text (https://github.com/benhurott/react-native-masked-text) using MaskService.

Example:

`maskMoneyService(value) {
    return MaskService.toMask(
      'money',
      value,
      {
        precision: 2,
        separator: ',',
        delimiter: '.',
        unit: 'R$ ',
        suffixUnit: ''
      });
  }`

I apply this function on ChangeText and Value fields on Input.

Bye
